import { theme } from '@/core/lib/theme';
import { AuthProvider } from '@/core/providers/auth-provider';
import { LocaleProvider } from '@/core/providers/locale-provider';
import { QueryProvider } from '@/core/providers/query-provider';
import {
  ColorSchemeScript,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/dropzone/styles.css';
import { ModalsProvider } from '@mantine/modals';
import { Notifications } from '@mantine/notifications';
import '@mantine/notifications/styles.css';
import '@mantine/spotlight/styles.css';
import { Locale } from '@org/prisma/browser';
import type { TokenPayload } from '@org/types/token';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import { headers } from 'next/headers';
import './global.css';
export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

function getUserFromHeaders(h: Headers): TokenPayload | null {
  const sub = h.get('x-user-sub');
  if (!sub) return null;

  const user: Record<string, unknown> = {};
  h.forEach((value, key) => {
    if (key.startsWith('x-user-')) {
      const field = key.slice('x-user-'.length);
      const decoded = decodeURIComponent(value);
      if (decoded === 'true') user[field] = true;
      else if (decoded === 'false') user[field] = false;
      else user[field] = decoded;
    }
  });
  return user as unknown as TokenPayload;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = await headers();
  const user = getUserFromHeaders(headersList);
  const locale = await getLocale();

  return (
    <html {...mantineHtmlProps} lang={locale}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="min-h-screen min-w-full">
        <QueryProvider>
          <AuthProvider user={user}>
            <NextIntlClientProvider>
              <MantineProvider defaultColorScheme="auto" theme={theme}>
                <Notifications />
                <ModalsProvider>
                  <LocaleProvider
                    locale={(locale?.toUpperCase() as Locale) || 'TR'}
                  >
                    {children}
                  </LocaleProvider>
                </ModalsProvider>
              </MantineProvider>
            </NextIntlClientProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
