import type {
  AdjustmentType,
  CurrencyCode,
  PriceListStatus,
  PriceListType,
  RoundingRule,
  SourceSystem,
} from '../../client.js';
import type { PricingStoreSlug } from './pricing-seed.config.js';
import { PRICING_SCENARIO_IDS } from './pricing-seed.config.js';

export type PricingAssignmentKind =
  | 'NONE'
  | 'ALL_CUSTOMERS'
  | 'CUSTOMER_GROUP'
  | 'CUSTOMER'
  | 'ORGANIZATION';

export type PricingRowTemplate =
  | 'BASE_FIXED'
  | 'PROMO_MIXED'
  | 'CUSTOMER_MIXED'
  | 'CUSTOMER_FIXED'
  | 'DRAFT_SALE'
  | 'ARCHIVED_FIXED'
  | 'CONTRACT_EXCHANGE'
  | 'CONTRACT_DRAFT';

export type PricingParentMode = 'NONE' | 'STORE_DEFAULT_BASE';

export interface PricingScenarioDefinition {
  id: string;
  name: string;
  description: string;
  storeSlug: PricingStoreSlug;
  type: PriceListType;
  status: PriceListStatus;
  isActive: boolean;
  defaultCurrencyCode: CurrencyCode;
  parentMode: PricingParentMode;
  assignmentKind: PricingAssignmentKind;
  priority: number;
  variantCount: number;
  rowTemplate: PricingRowTemplate;
  validFromOffsetDays: number | null;
  validToOffsetDays: number | null;
  listAdjustmentType: AdjustmentType | null;
  listAdjustmentValue: number | null;
  sourceSystem: SourceSystem;
  isSourceLocked: boolean;
  isExchangeRateDerived: boolean;
  sourceCurrencyCode: CurrencyCode | null;
  roundingRule: RoundingRule;
  contractRef: string | null;
}

export const PRICING_SCENARIOS: readonly PricingScenarioDefinition[] = [
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][0],
    name: 'Helix Magaza Seed Base USD',
    description: 'Seeded USD base list for storefront-style pricing coverage.',
    storeSlug: 'helix-magaza',
    type: 'BASE',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'USD',
    parentMode: 'NONE',
    assignmentKind: 'NONE',
    priority: 10,
    variantCount: 6,
    rowTemplate: 'BASE_FIXED',
    validFromOffsetDays: null,
    validToOffsetDays: null,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'INTERNAL',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][1],
    name: 'Helix Magaza Seed Sale Campaign',
    description: 'Active public campaign list with relative sale rows.',
    storeSlug: 'helix-magaza',
    type: 'SALE',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'TRY',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'ALL_CUSTOMERS',
    priority: 60,
    variantCount: 8,
    rowTemplate: 'PROMO_MIXED',
    validFromOffsetDays: -7,
    validToOffsetDays: 30,
    listAdjustmentType: 'PERCENTAGE',
    listAdjustmentValue: 10,
    sourceSystem: 'INTERNAL',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][2],
    name: 'Helix Magaza Seed VIP Custom',
    description: 'VIP customer-group price list seeded for premium shoppers.',
    storeSlug: 'helix-magaza',
    type: 'CUSTOM',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'EUR',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'CUSTOMER_GROUP',
    priority: 80,
    variantCount: 7,
    rowTemplate: 'CUSTOMER_MIXED',
    validFromOffsetDays: -2,
    validToOffsetDays: 45,
    listAdjustmentType: 'FIXED_AMOUNT',
    listAdjustmentValue: 15,
    sourceSystem: 'CSV_IMPORT',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][3],
    name: 'Helix Magaza Seed Customer Offer',
    description: 'Customer-specific active offer list for one seeded customer.',
    storeSlug: 'helix-magaza',
    type: 'CUSTOM',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'GBP',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'CUSTOMER',
    priority: 90,
    variantCount: 6,
    rowTemplate: 'CUSTOMER_FIXED',
    validFromOffsetDays: -1,
    validToOffsetDays: 21,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'API',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][4],
    name: 'Helix Magaza Seed Sale Draft',
    description: 'Future-dated sale draft for workflow coverage.',
    storeSlug: 'helix-magaza',
    type: 'SALE',
    status: 'DRAFT',
    isActive: false,
    defaultCurrencyCode: 'TRY',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'ALL_CUSTOMERS',
    priority: 40,
    variantCount: 6,
    rowTemplate: 'DRAFT_SALE',
    validFromOffsetDays: 7,
    validToOffsetDays: 45,
    listAdjustmentType: 'PERCENTAGE',
    listAdjustmentValue: 6,
    sourceSystem: 'INTERNAL',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-magaza'][5],
    name: 'Helix Magaza Seed Custom Archived',
    description: 'Archived custom list with expired prices.',
    storeSlug: 'helix-magaza',
    type: 'CUSTOM',
    status: 'ARCHIVED',
    isActive: false,
    defaultCurrencyCode: 'EUR',
    parentMode: 'NONE',
    assignmentKind: 'NONE',
    priority: 5,
    variantCount: 4,
    rowTemplate: 'ARCHIVED_FIXED',
    validFromOffsetDays: -90,
    validToOffsetDays: -30,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'MANUAL_IMPORT',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][0],
    name: 'Helix Toptan Seed Base EUR',
    description: 'Seeded EUR base list for wholesale pricing coverage.',
    storeSlug: 'helix-toptan',
    type: 'BASE',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'EUR',
    parentMode: 'NONE',
    assignmentKind: 'NONE',
    priority: 10,
    variantCount: 6,
    rowTemplate: 'BASE_FIXED',
    validFromOffsetDays: null,
    validToOffsetDays: null,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'INTERNAL',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][1],
    name: 'Helix Toptan Seed Sale Wholesale',
    description: 'Broad wholesale sale list with public assignment coverage.',
    storeSlug: 'helix-toptan',
    type: 'SALE',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'TRY',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'ALL_CUSTOMERS',
    priority: 55,
    variantCount: 8,
    rowTemplate: 'PROMO_MIXED',
    validFromOffsetDays: -5,
    validToOffsetDays: 35,
    listAdjustmentType: 'PERCENTAGE',
    listAdjustmentValue: 8,
    sourceSystem: 'INTERNAL',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][2],
    name: 'Helix Toptan Seed Reseller Custom',
    description: 'Reseller-focused custom list assigned to a seeded customer group.',
    storeSlug: 'helix-toptan',
    type: 'CUSTOM',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'USD',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'CUSTOMER_GROUP',
    priority: 75,
    variantCount: 7,
    rowTemplate: 'CUSTOMER_MIXED',
    validFromOffsetDays: -3,
    validToOffsetDays: 60,
    listAdjustmentType: 'FIXED_AMOUNT',
    listAdjustmentValue: 25,
    sourceSystem: 'MANUAL_IMPORT',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][3],
    name: 'Helix Toptan Seed Organization Contract',
    description: 'Exchange-derived contract list assigned to a seeded organization.',
    storeSlug: 'helix-toptan',
    type: 'CONTRACT',
    status: 'ACTIVE',
    isActive: true,
    defaultCurrencyCode: 'GBP',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'ORGANIZATION',
    priority: 95,
    variantCount: 8,
    rowTemplate: 'CONTRACT_EXCHANGE',
    validFromOffsetDays: -2,
    validToOffsetDays: 45,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'SAP',
    isSourceLocked: false,
    isExchangeRateDerived: true,
    sourceCurrencyCode: 'USD',
    roundingRule: 'ROUND_99',
    contractRef: 'CNTR-HT-2026-001',
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][4],
    name: 'Helix Toptan Seed Contract Draft',
    description: 'Future-dated draft contract list for approval workflows.',
    storeSlug: 'helix-toptan',
    type: 'CONTRACT',
    status: 'DRAFT',
    isActive: false,
    defaultCurrencyCode: 'EUR',
    parentMode: 'STORE_DEFAULT_BASE',
    assignmentKind: 'ORGANIZATION',
    priority: 70,
    variantCount: 6,
    rowTemplate: 'CONTRACT_DRAFT',
    validFromOffsetDays: 10,
    validToOffsetDays: 70,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'SAP',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: 'CNTR-HT-2026-DRAFT',
  },
  {
    id: PRICING_SCENARIO_IDS['helix-toptan'][5],
    name: 'Helix Toptan Seed Custom Archived',
    description: 'Archived wholesale custom list with expired coverage.',
    storeSlug: 'helix-toptan',
    type: 'CUSTOM',
    status: 'ARCHIVED',
    isActive: false,
    defaultCurrencyCode: 'USD',
    parentMode: 'NONE',
    assignmentKind: 'NONE',
    priority: 5,
    variantCount: 4,
    rowTemplate: 'ARCHIVED_FIXED',
    validFromOffsetDays: -120,
    validToOffsetDays: -40,
    listAdjustmentType: null,
    listAdjustmentValue: null,
    sourceSystem: 'CSV_IMPORT',
    isSourceLocked: false,
    isExchangeRateDerived: false,
    sourceCurrencyCode: null,
    roundingRule: 'NONE',
    contractRef: null,
  },
] as const;
